# Generated by Django 3.2.4 on 2021-07-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='nombre',
            new_name='modelo',
        ),
    ]
